# Generated by Django 4.1.3 on 2022-12-14 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage_sensors", "0003_rename_name_sensor_sensors_sensor_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name="sensors",
            old_name="date",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="sensors",
            name="sensor_name",
        ),
        migrations.RemoveField(
            model_name="sensors",
            name="value",
        ),
        migrations.CreateModel(
            name="SensorsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=20)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="storage_sensors.sensors",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sensors",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="storage_sensors.sensorstype",
            ),
        ),
    ]
