# Generated by Django 4.1.3 on 2022-12-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage_sensors", "0004_sensorstype_rename_date_sensors_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("second_name", models.CharField(max_length=20)),
                ("user_id", models.CharField(max_length=20)),
            ],
        ),
    ]
