# Generated by Django 4.1.3 on 2022-12-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage_sensors", "0005_employee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="second_name",
            new_name="last_name",
        ),
    ]
