# Generated by Django 4.1.3 on 2022-12-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage_sensors", "0007_machines_positions_schedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="login",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
