# Generated by Django 4.1.3 on 2022-12-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage_sensors", "0008_employee_login"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensors",
            old_name="machines_type",
            new_name="machine",
        ),
    ]
