# Generated by Django 4.1.3 on 2023-01-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage_sensors", "0015_alter_prediction_detail_alter_prediction_type_alert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorsdata",
            name="value",
            field=models.FloatField(),
        ),
    ]
